#!/usr/bin/env bash
# Generate (or check) the <MEMORY_ROOT>/TREE.md index files — one per discipline + a root index.
# Config-driven (.memory-tree.conf: MEMORY_ROOT, DISCIPLINES). Deterministic by construction: tracked
# files only (git ls-files), LC_ALL=C sort, LF, no timestamps, fixed header. Depth-capped to
# build-folder granularity so every TREE.md fits the caps (part of the memory-tree hygiene kit).
#
#   memory-tree/gen-memory-tree.sh --write   # (re)generate every TREE.md to disk
#   memory-tree/gen-memory-tree.sh --check    # diff each against its tracked file; non-zero on drift (default)
set -u
export LC_ALL=C
ROOT="$(git rev-parse --show-toplevel)" || exit 2
cd "$ROOT" || exit 2
MEMORY_ROOT=memory
DISCIPLINES="architecture deployment blocks design performance"
[ -f "$ROOT/.memory-tree.conf" ] && . "$ROOT/.memory-tree.conf"
M="$MEMORY_ROOT"
# codebase-map kit interop: a MAP_ROOT that is a direct child of this tree must appear in the
# root TREE.md render (a dir the loop doesn't know about would silently vanish from the index).
MAP_SUB=""
if [ -f "$ROOT/.codebase-map.conf" ]; then
  _cbm_root=$(. "$ROOT/.codebase-map.conf" 2>/dev/null; printf '%s' "${MAP_ROOT:-}" | tr -d '\r')
  _cbm_root="${_cbm_root%/}"   # trailing slash would mis-read a direct child as nested
  case "$_cbm_root" in "$M"/*) _s="${_cbm_root#"$M"/}"; case "$_s" in */*) ;; *) MAP_SUB="$_s";; esac;; esac
fi
HEADER='<!-- generated by the memory-tree gen script (--write) — do not hand-edit -->'
MODE="${1:---check}"

_children() {  # $1 = tracked-path prefix WITHOUT trailing slash
  local pfx="$1" depth
  depth=$(awk -F/ '{print NF}' <<<"$pfx")
  git ls-files "$pfx/*" \
    | awk -F/ -v d="$depth" '{ if (NF == d+1) print $(d+1); else print $(d+1) "/" }' \
    | sort -u
}

_render_discipline() {  # $1 = discipline
  local disc="$1" f sub
  printf '%s\n' "$HEADER"
  printf '# %s/%s/ — generated tree index\n\n' "$M" "$disc"
  printf '%s/%s/\n' "$M" "$disc"
  for f in README.md TREE.md DECISIONS.md BACKLOG.md; do
    [ -f "$M/$disc/$f" ] && printf '  %s\n' "$f"
  done
  for sub in decisions guides archive builds; do
    git ls-files "$M/$disc/$sub/*" | grep -q . || continue
    printf '  %s/\n' "$sub"
    if [ "$sub" = builds ]; then
      # folder names ONLY (depth cap) — path = $M/<disc>/builds/<folder>/...  (fields: M disc builds folder)
      git ls-files "$M/$disc/builds/*" | awk -F/ '{print $4}' | sort -u \
        | while IFS= read -r n; do printf '    %s/\n' "$n"; done
    else
      _children "$M/$disc/$sub" | while IFS= read -r n; do printf '    %s\n' "$n"; done
    fi
  done
}

_render_root() {
  local f d
  printf '%s\n' "$HEADER"
  printf '# %s/ — generated root tree index\n\n' "$M"
  printf '%s/\n' "$M"
  for f in README.md TREE.md HYGIENE.md TEMPLATE-SPEC.md; do [ -f "$M/$f" ] && printf '  %s\n' "$f"; done
  for d in project ${MAP_SUB:+$MAP_SUB} $DISCIPLINES; do
    git ls-files "$M/$d/*" | grep -q . && printf '  %s/\n' "$d"
  done
}

_target() { [ "$1" = root ] && echo "$M/TREE.md" || echo "$M/$1/TREE.md"; }
_render() { [ "$1" = root ] && _render_root || _render_discipline "$1"; }

status=0
UNITS="root $DISCIPLINES"
case "$MODE" in
  --write) for u in $UNITS; do _render "$u" > "$(_target "$u")"; done ;;
  --check)
    for u in $UNITS; do
      t=$(_target "$u"); tmp=$(mktemp); _render "$u" > "$tmp"
      if [ ! -f "$t" ] || ! diff -q --strip-trailing-cr "$t" "$tmp" >/dev/null 2>&1; then
        echo "TREE.md STALE ($t) — run: memory-tree/gen-memory-tree.sh --write"; status=1
      fi
      rm -f "$tmp"
    done ;;
  *) echo "usage: $0 [--write|--check]"; exit 2 ;;
esac
exit "$status"
